In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [5]:
score=np.array([[55,89,76,65,48,70],[60,85,60,68,np.nan,60],[65,90,82,72,66,77]])

In [20]:
score

array([[55., 89., 76., 65., 48., 70.],
       [60., 85., 60., 68., nan, 60.],
       [65., 90., 82., 72., 66., 77.]])

In [43]:
#各科平均
e_mean=np.mean((english_score))
m_mean=np.nanmean(math_score)
c_mean=np.mean(chinese_score)

(e_mean,m_mean,c_mean)

(67.16666666666667, 66.6, 75.33333333333333)

In [46]:
#各科最大值
e_max=np.nanmax([55,89,76,65,48,70])
m_max=np.nanmax([60,85,60,68,np.nan,60])
c_max=np.nanmax([65,90,82,72,66,77])
(e_max,m_max,c_max)

(89, 85.0, 90)

In [50]:
#各科最小值
e_min=np.nanmin([55,89,76,65,48,70])
m_min=np.nanmin([60,85,60,68,np.nan,60])
c_min=np.nanmin([65,90,82,72,66,77])
(e_min,m_min,c_min)

(48, 60.0, 65)

In [51]:
#各科標準差
e_std=np.nanstd([55,89,76,65,48,70])
m_std=np.nanstd([60,85,60,68,np.nan,60])
c_std=np.nanstd([65,90,82,72,66,77])
(e_std,m_std,c_std)

(13.433995020924426, 9.707728879609279, 8.825468196582484)

#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [53]:
m = np.array([60,85,60,68,55,60])

In [54]:
mean=np.mean(m)
max=np.nanmax(m)
min=np.nanmin(m)
std=np.nanstd(m)
(mean,max,min,std)

(64.66666666666667, 85, 55, 9.860132971832694)

#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [60]:
e_corr=np.corrcoef([65,90,82,72,66,77],[55,89,76,65,48,70])
m_corr=np.corrcoef([65,90,82,72,66,77],[60,85,60,68,np.nan,60])
(e_corr,m_corr)

(array([[1.        , 0.97792828],
        [0.97792828, 1.        ]]),
 array([[ 1., nan],
        [nan, nan]]))